apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases

spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:18

  # Let CNPG handle primary failover automatically.
  primaryUpdateStrategy: unsupervised

  # Spread PostgreSQL instances across different K3s nodes.
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  # PostgreSQL data.
  storage:
    storageClass: longhorn
    size: 20Gi

  # PostgreSQL WAL on a separate Longhorn volume.
  walStorage:
    storageClass: longhorn
    size: 10Gi