apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: larapaperdata-pvc
  namespace: trmnl 
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 10Gi 
  storageClassName: longhorn  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: larapaperdb-pvc
  namespace: trmnl 
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 10Gi 
  storageClassName: longhorn  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: larapaper            
  namespace: trmnl      
spec:
  replicas: 1        
  selector:
    matchLabels:
      app: larapaper         
  template:
    metadata:
      labels:
        app: larapaper       
    spec:
      containers:
      - name: larapaper      
        image: ghcr.io/usetrmnl/larapaper:latest        
        ports:
        - containerPort: 8080
        env:
          - name: APP_KEY
            value: "dRUPNvJ8pw6D6s/+WSBV7mUs75EWLAT9qc24zsed2xQ="
          - name: APP_URL
            value: "https://larapaper.beanieiscool.com" 
          - name: PHP_OPCACHE_ENABLE
            value: "1"
          - name: TRMNL_PROXY_REFRESH_MINUTES
            value: "15"
        volumeMounts:
        - name: larapaper-data
          mountPath: /var/www/html/storage/app/public/images/generated
        - name: larapaper-db
          mountPath: /var/www/html/database/storage
      volumes:
      - name: larapaper-data
        persistentVolumeClaim:
          claimName: larapaperdata-pvc
      - name: larapaper-db
        persistentVolumeClaim:
          claimName: larapaperdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: larapaper
  namespace: trmnl
spec:
  selector:
    app: larapaper
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: larapaper-ingress
  namespace: trmnl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: larapaper.beanieiscool.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: larapaper
            port:
              number: 80
  tls:
  - hosts:
    - larapaper.beanieiscool.com
    secretName: larapaper-cert
