---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-data
  namespace: adguard
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      containers:
        - name: adguardhome
          image: adguard/adguardhome:latest
          ports:
            - name: http
              containerPort: 3000   # setup UI
            - name: web
              containerPort: 80     # main UI
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/conf
            - name: work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: adguardhome-data
        - name: work
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adguardhome
  namespace: adguard
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.210     # MetalLB IP
  selector:
    app: adguardhome
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguardhome
  namespace: adguard
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: dns.beanieiscool.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguardhome
                port:
                  number: 80
  tls:
    - hosts:
        - dns.beanieiscool.com
      secretName: adguardhome-tls