apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-pvc
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 5gi 
  storageClassName: longhorn 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma            
  namespace: monitoring      
spec:
  replicas: 1        
  selector:
    matchLabels:
      app: uptimekuma         
  template:
    metadata:
      labels:
        app: uptimekuma       
    spec:
      containers:
      - name: uptimekuma      
        image: louislam/uptime-kuma:2        
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: uptimekuma-data
          mountPath: /app/data
      volumes:
      - name: uptimekuma-data
        persistentVolumeClaim:
          claimName: uptimekuma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uptimekuma
  namespace: monitoring
spec:
  selector:
    app: uptimekuma
  ports:
  - port: 80
    targetPort: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: kuma.beanieiscool.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptimekuma
            port:
              number: 80
  tls:
  - hosts:
    - kuma.beanieiscool.com
    secretName: uptimekuma-cert
