apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox
  namespace: monitoring-external
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchLabels:
      app: proxmox
  namespaceSelector:
    matchNames:
      - monitoring-external
  endpoints:
    - port: metrics
      interval: 30s
