apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  version: v1.34.2+k3s1   # <-- change this if upgrading
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - key: DedicatedControlPlane
      operator: Exists
      effect: NoSchedule
  upgrade:
    image: rancher/k3s-upgrade
