---
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-upgrade
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["upgrade.cattle.io"]
  resources: ["plans", "plans/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-upgrade
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-upgrade-controller
  template:
    metadata:
      labels:
        app: system-upgrade-controller
    spec:
      serviceAccountName: system-upgrade
      tolerations:
        - key: DedicatedControlPlane
          operator: Exists
          effect: NoSchedule
      containers:
      - name: system-upgrade-controller
        image: rancher/system-upgrade-controller:v0.13.3
        imagePullPolicy: IfNotPresent
        args:
          - --controller-threads=2
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi

---
# =================================
#   K3S SERVER PLAN (CONTROL-PLANE)
# =================================
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server-plan
  namespace: system-upgrade
spec:
  version: v1.33.5+k3s1
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - key: DedicatedControlPlane
      operator: Exists
      effect: NoSchedule
  upgrade:
    image: rancher/k3s-upgrade

---
# =================================
#   K3S AGENT PLAN (WORKERS)
# =================================
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-plan
  namespace: system-upgrade
spec:
  version: v1.33.5+k3s1
  concurrency: 3
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  upgrade:
    image: rancher/k3s-upgrade