apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-bot-pvc
  namespace: discord-bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
