apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-pvc
  namespace: external
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 5Gi 
  storageClassName: longhorn 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr            
  namespace: external      
spec:
  replicas: 1        
  selector:
    matchLabels:
      app: seerr         
  template:
    metadata:
      labels:
        app: seerr       
    spec:
      containers:
      - name: seerr      
        image: ghcr.io/seerr-team/seerr:latest
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: seerr-data
          mountPath: /app/config
      volumes:
      - name: seerr-data
        persistentVolumeClaim:
          claimName: seerr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: external
spec:
  selector:
    app: seerr
  ports:
  - port: 80
    targetPort: 5055
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerr-ingress
  namespace: external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod 
spec:
  ingressClassName: traefik         
  rules:
  - host: seerr.beanieiscool.com      
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seerr
            port:
              number: 80
  tls:
  - hosts:
    - seerr.beanieiscool.com
    secretName: seerr-cert