apiVersion: v1
kind: Namespace
metadata:
  name: arrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-data-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  namespace: arrstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanuparr
  template:
    metadata:
      labels:
        app: cleanuparr
    spec:
      containers:
      - name: cleanuparr
        image: ghcr.io/cleanarr/cleanuparr:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: ghcr-cred
        env:
          - name: TZ
            value: "America/Chicago"
          - name: PORT
            value: "11011"
        volumeMounts:
          - name: cleanuparr-data
            mountPath: /config
      volumes:
        - name: cleanuparr-data
          persistentVolumeClaim:
            claimName: cleanuparr-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
  namespace: arrstack
spec:
  selector:
    app: cleanuparr
  ports:
  - port: 80
    targetPort: 11011
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleanuparr-ingress
  namespace: arrstack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: cleanuparr.HOSTNAME.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cleanuparr
            port:
              number: 80
  tls:
  - hosts:
    - cleanuparr.HOSTNAME.com
    secretName: cleanuparr-cert
