apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapowarr-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 2Gi 
  storageClassName: longhorn 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapowarr            
  namespace: arrstack      
spec:
  replicas: 1        
  selector:
    matchLabels:
      app: kapowarr         
  template:
    metadata:
      labels:
        app: kapowarr       
    spec:
      containers:
      - name: kapowarr      
        image: mrcas/kapowarr:latest        
        ports:
        - containerPort: 5656
        volumeMounts:
        - name: kapowarr-data
          mountPath: /app/db
        - name: comics
          mountPath: /comics
      volumes:
      - name: kapowarr-data
        persistentVolumeClaim:
          claimName: kapowarr-pvc
      - name: comics
        nfs:
            server: 192.168.0.222
            path: /comics
---
apiVersion: v1
kind: Service
metadata:
  name: kapowarr
  namespace: arrstack
spec:
  selector:
    app: kapowarr
  ports:
  - port: 80
    targetPort: 5656
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kapowarr-ingress
  namespace: arrstack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: kapowarr.HOSTNAME.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kapowarr
            port:
              number: 80
  tls:
  - hosts:
    - kapowarr.HOSTNAME.com
    secretName: kapowarr-cert
