apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr            
  namespace: arrstack      
spec:
  replicas: 1       
  selector:
    matchLabels:
      app: prowlarr      
  template:
    metadata:
      labels:
        app: prowlarr     
    spec:
      containers:
      - name: prowlarr      
        image: linuxserver/prowlarr        
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: prowlarr-data
          mountPath: /config
      volumes:
      - name: prowlarr-data
        persistentVolumeClaim:
          claimName: prowlarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arrstack
spec:
  selector:
    app: prowlarr
  ports:
  - port: 80
    targetPort: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-ingress
  namespace: arrstack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: prowlarr.HOSTNAME.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 80
  tls:
  - hosts:
    - prowlarr.HOSTNAME.com
    secretName: prowlarr-cert
